/*
 * This source file was generated by the Gradle 'init' task
 */
package d.engine;

import d.engine.geomety.Point3D;
import d.engine.geomety.PositionVector3D;
import d.engine.geomety.ScreenPlane;
import d.engine.geomety.Shape3D;
import d.engine.geomety.Triangle;
import d.engine.gui.SingleShapeWindow;

public class App {

    public static void main(String[] args) {
        Point3D A = new Point3D(0, 0, 0);
        Point3D B = new Point3D(1, 0, 0);
        Point3D C = new Point3D(0.5, Math.sqrt(3) / 2, 0);
        Point3D D = new Point3D(0.5, Math.sqrt(3) / 6, Math.sqrt(6) / 3);

        // Define the faces (triangles)
        Triangle triangle1 = new Triangle(A, B, C);  // Face ABC
        Triangle triangle2 = new Triangle(A, B, D);  // Face ABD
        Triangle triangle3 = new Triangle(B, C, D);  // Face BCD
        Triangle triangle4 = new Triangle(A, C, D);  // Face ACD

        Triangle[] triangles = new Triangle[] {triangle1, triangle2, triangle3, triangle4};

        Shape3D tetrahedron = new Shape3D(triangles);

        tetrahedron.applyScalar(1);
        System.out.println("Vertex A after scaling: " + A);


        tetrahedron.setPosition(new PositionVector3D(0, 0, 0));

        ScreenPlane screenPlane = new ScreenPlane(new PositionVector3D(0, 0, -0.5),
                                                  new PositionVector3D(0, 0, 1));

        new SingleShapeWindow(tetrahedron, screenPlane);

        System.out.println("Unique vertices: " + tetrahedron.vertices.size());
        System.err.println(tetrahedron);



    }
}
