/*
 * This source file was generated by the Gradle 'init' task
 */
package d.engine;

import d.engine.geomety.Point3D;
import d.engine.geomety.Triangle;
import d.engine.gui.window;;

public class App {

    public static void main(String[] args) {
        Triangle triangle = new Triangle(new Point3D(0, 0, 0),
                                         new Point3D(1, 0, 0),
                                         new Point3D(1, 1, 1));

        new window();

        System.out.println("hello");
    }
}
